spring:
  application:
    name: retailsphere

  datasource:
    url: jdbc:mysql://localhost:3306/retailsphere
    username: retailsphere
    password: RetailSphere@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080
