[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/mumbai-region.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[bastion]
bastion01 ansible_host=10.0.1.202

[developer]
developer01 ansible_host=10.0.1.228

[infra]
infra01 ansible_host=10.0.1.164

[jenkins]
jenkins01 ansible_host=10.0.1.186

[kubeadm:children]
kubeadm_master
kubeadm_worker

[kubeadm_master]
kubeadm-master01 ansible_host=10.0.1.97

[kubeadm_worker]
kubeadm-worker01 ansible_host=10.0.1.68

