[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/mumbai-region.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[bastion]
bastion01 ansible_host=10.0.1.6

[developer]
developer01 ansible_host=10.0.1.119

[infra]
infra01 ansible_host=10.0.1.149

[jenkins]
jenkins01 ansible_host=10.0.1.228

[kubeadm-master]
kubeadm-master01 ansible_host=10.0.1.100

[kubeadm-worker]
kubeadm-worker01 ansible_host=10.0.1.71

