apiVersion: v1
kind: ConfigMap
metadata:
  name: retailsphere-config
  namespace: retailsphere

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/retailsphere
  SPRING_DATASOURCE_USERNAME: retailuser
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_PROFILES_ACTIVE: dev
