apiVersion: v1
kind: Secret
metadata:
  name: retailsphere-secret
  namespace: retailsphere

type: Opaque

stringData:
  SPRING_DATASOURCE_PASSWORD: Retail@123
  JWT_SECRET: RetailSphereSecretKey2026
