---
ingress_namespace: ingress-nginx

ingress_manifest: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

ingress_controller_name: ingress-nginx-controller

