---
- name: Prepare all nodes (common)
  hosts: kubeadm_master
  become: yes
  roles:
    - kubeadm-cluster

- name: Prepare all nodes (common)
  hosts: kubeadm_worker
  become: yes
  roles:
    - kubeadm-cluster

- name: Initialize Kubernetes master
  hosts: kubeadm_master
  become: yes
  roles:
    - kubeadm-master

- name: Install MetalLB
  hosts: kubeadm_master
  become: yes
  roles:
    - metallb

- name: Join worker nodes
  hosts: kubeadm_worker
  become: yes
  roles:
    - kubeadm-worker

