## MetalLB, Ingress, Metrics Server, Dashboard...
---
- name: Install MetalLB
  hosts: kubeadm_master
  become: yes
  tags:
    - metallb
  roles:
    - metallb

- name: Install Ingress NGINX
  hosts: kubeadm_master
  become: yes
  tags:
    - ingress
  roles:
    - ingress-nginx

- name: Configure Nginx Reverse Proxy
  hosts: bastion
  become: yes
  tags:
    - nginx
  roles:
    - nginx-reverse-proxy
