## MetalLB, Ingress, Metrics Server, Dashboard...
---
- name: Install MetalLB
  hosts: kubeadm_master
  become: yes
  tags:
    - metallb
  roles:
    - metallb

- name: Install Ingress NGINX
  hosts: kubeadm_master
  become: yes
  tags:
    - ingress
  roles:
    - ingress-nginx

- name: Configure Nginx Reverse Proxy
  hosts: kubeadm_master
  become: yes
  tags:
    - nginx
  roles:
    - nginx-reverse-proxy

- name: Install Argo CD
  hosts: kubeadm_master
  become: yes
  tags:
    - argocd 
  roles:
    - argocd

- name: Install Local Path Provisioner
  hosts: kubeadm_master
  become: yes
  tags:
    - local Path
  roles:
    - local-path-provisioner

- name: Install Monitoring Stack
  hosts: kubeadm_master
  become: yes
  tags:
    - monitoring
  roles:
    - monitoring-stack
