---
- hosts: bastion
  become: true
  roles:
    - common
    - bastion

- hosts: developer
  become: true
  roles:
    - common
    - developer

- hosts: infra
  become: true
  roles:
    - common
    - infra

- hosts: jenkins
  become: true
  roles:
    - common
    - jenkins

- hosts: bastion
  become: true
  roles:
    - common
    - bastion
    - nginx
