apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: retailsphere
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: Root@123
  MYSQL_DATABASE: retailsphere
  MYSQL_USER: retailuser
  MYSQL_PASSWORD: Retail@123
